### PR TITLE
OpenStack codename lookup by charm name and workload version

### PR DESCRIPTION
**Pull request by gabrielcocenza**
- lookup function that return the latest compatible OpenStack codename.
- removed zaza functions to get openstack release based on workload version.
- added csv file with min and max versions for OpenStack services.

### CODE REVIEW

File: cou/utils/openstack.py [hunk 1]
```diff
@@ -13,118 +13,125 @@
...
+            (
+                "Not possible to find a compatible Openstack codename for "
+                "charm: %s with workload_version: %s"
+            ),
+            charm,
+            workload_version,
+        )
+        return None
+    for openstack_release, versions in OPENSTACK_LOOKUP[charm].items():
+        if versions.minor and not versions.micro:
```
[the remark this answers is not in the document]
Comment (aieri) [reply cou/utils/openstack.py:124]: I think I understand. You are using the inclusive ranges shown in the releases pages, but that's very unwieldy when you cannot for sure know what the last available version is (and it theoretically change in the future due to backports). When you then mix components that span multiple versions, and components whose boundaries are not on a major version it becomes a mess. I think you really need to use exclusive ranges.

Here's another suggestion: store the lookup table directly as python objects, and use a Container to more naturally implement (exclusive) range checks and prevent the whole data structure from becoming unwieldy.

For example:

```
# These are your custom ranges
@dataclass
class VersionRange(Container):
    lower: str
    upper: str

    def __contains__(self, version):
        testver = Version(version)
        lowerver = Version(self.lower)
        upperver = Version(self.upper)
        # note the exclusive range
        return testver >= lowerver and testver < upperver
```

Then you can define your mapping, including possible aliases to make things more compact
```
octopus = VersionRange('15.2', '16')

lookup = {
    'ceph': {
        'ussuri': octopus,
        'victoria': octopus,
    },
    'nova': {
        'ussuri': VersionRange('21', '22'),
        'victoria': VersionRange('22', '23'),
    }
}
```

At this point you can use list comprehensions relatively readably:
```
In [16]: [codename for codename, ver_range in lookup['ceph'].items() if '15.5' in ver_range]
Out[16]: ['ussuri', 'victoria']
```

You _could_ still store all your values in a table for easier updating down the line (adding a new release to the lookup dict would not be fun), though mapping a VersionRange object to a cell (or a pair of cells) would not be very straightforward

File: tests/unit/utils/test_openstack.py [hunk 2]
```diff
@@ -13,18 +13,33 @@
...
+            ["victoria", "xena", "yoga"],
+        ),  # version 15 (octopus) can be ussuri or victoria, we return the latest (victoria)
+        # version 16 (pacific) can be wallaby or xena, we return the latest (xena)
+        ("gnocchi", ["4.3.4", "4.4.0", "4.4.1"], ["ussuri", "wallaby", "yoga"]),  # micro
+        (
+            "openstack-dashboard",
+            ["18.3.5", "18.6.3", "19.3.0", "20.1.4", "20.2.0"],
+            ["ussuri", "victoria", "wallaby", "xena", "yoga"],
+        ),  # minor
+        ("my_charm", ["13.1.2"], [None]),  # non-existent
```
Comment (aieri) [inline tests/unit/utils/test_openstack.py:39]: this tests looking up a non-existent charm; you probably want to also test an out-of-bounds version for a known charm

**Review by aieri — CHANGES_REQUESTED** [review]
This is looking promising! I have added several suggestions on how to simplify the lookup.
Also, please link this PR to issue 15.

File: cou/utils/openstack.py [hunk 3]
```diff
@@ -13,118 +13,125 @@
...
-    :returns: Codename for OVN
-    :rtype: string
-    """
-    return _get_special_codename(version, OVN_CODENAMES)
+def generate_openstack_lookup() -> OrderedDict:
+    """Generate an OpenStack lookup dictionary based on the version of the components.
+
+    The dictionary is generated thru an static csv file that should be update regularly
+    to include new Openstack releases and update the min and max versions of the services.
+    The csv table is made from the release page [0] charm delivery [1], cmadison and rmadison.
```
[the remark this answers is not in the document]
Comment (gabrielcocenza) [reply cou/utils/openstack.py:40]: I used rmadison for `bind9` (package that sets the workload version on designate-bind) and used cmadison on `gnocchi`

File: cou/utils/openstack.py [hunk 4]
```diff
@@ -13,118 +13,125 @@
...
+                    True if micro == "TRUE" else False,
+                )
+            openstack_lookup[service] = service_dict
+    for charm_type, charms in charms_types.items():
+        for charm in charms:
+            openstack_lookup[charm] = openstack_lookup[charm_type]
+    return openstack_lookup
+
+
+OPENSTACK_LOOKUP = generate_openstack_lookup()
```
[the remark this answers is not in the document]
Comment (gabrielcocenza) [reply cou/utils/openstack.py:96]: It's probably not a performance issue, but does it worth generating the same lookup dictionary every time that we want to check a possible OpenStack release for a certain service? This really look like a global variable to me that it needs to be rendered once.

File: cou/utils/openstack.py [hunk 5]
```diff
@@ -13,118 +13,125 @@
...
+
+
+def get_latest_compatible_openstack_codename(
```
[the remark this answers is not in the document]
Comment (gabrielcocenza) [reply cou/utils/openstack.py:99]: Luckily I thought about this and it's just return the list instead of the last element. It's already ordered by OpenStack releases.

File: cou/utils/os_versions.py
[the remark this answers is not in the document]
Comment (gabrielcocenza) [reply cou/utils/os_versions.py:1]: We'll probably need `CompareOpenStack` in a close future to be able to sort OpenStack releases among applications. However, we can remove completely this file and add this class when necessary.

File: cou/utils/openstack.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (gabrielcocenza) [reply cou/utils/openstack.py:124]: I liked this idea and I think it can simplify the logic. 
If I understood correctly, the `lower` is considered the min version of a release `N` while `upper` is the min version of the release `N+1`. I'm curious how we can identify the OpenStack code name when we are at the latest possible release.

File: cou/utils/openstack.py [hunk 6]
```diff
@@ -13,118 +13,125 @@
...
+    charms_types = {
+        "ceph": ["ceph-mon", "ceph-fs", "ceph-radosgw", "ceph-osd"],
+        "swift": ["swift-proxy", "swift-storage"],
+        "nova": ["nova-cloud-controller", "nova-compute"],
+        "ovn": ["ovn-dedicated-chassis", "ovn-central"],
+        "neutron": ["neutron-api", "neutron-gateway"],
+        "manila": ["manila-ganesha"],
+        "horizon": ["openstack-dashboard"],
+    }
+    with open("cou/utils/openstack_lookup.csv") as csv_file:
```
Comment (rgildein) [inline cou/utils/openstack.py:66]: The path should be defined as constant.

File: cou/utils/openstack.py [hunk 7]
```diff
@@ -13,118 +13,125 @@
...
+                os_version, _ = header[column_index].split("-")
+                min_version = row[column_index]
+                max_version = row[column_index + 1]
+                service_dict[os_version] = Versions(
+                    Version(min_version),
+                    Version(max_version),
+                    True if minor == "TRUE" else False,
+                    True if micro == "TRUE" else False,
+                )
+            openstack_lookup[service] = service_dict
```
Comment (rgildein) [inline cou/utils/openstack.py:89]: Can we pack this to separate function, e.g. parse_csv_line?

File: cou/utils/openstack.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (rgildein) [reply cou/utils/openstack.py:96]: I partially agree with Gabriel, but I do not like idea defining constant in the middle of file. What if we defined `OPENSTACK_LOOKUP` as class object and use `__new__` so the generate will be called only once during one call. What do you say?

[the remark this answers is not in the document]
Comment (rgildein) [reply cou/utils/openstack.py:96]: Also this object can contain function the get (latest) o7k code-names.

File: tests/unit/utils/test_openstack.py [hunk 8]
```diff
@@ -13,18 +13,33 @@
...
     ],
 )
-def test_get_os_code_info(package, pkg_version, result):
-    actual = get_os_code_info(package, pkg_version)
-    assert result == actual
+def test_get_os_code_info(charm, workload_versions, results):
+    for index in range(len(workload_versions)):
```
Comment (rgildein) [inline tests/unit/utils/test_openstack.py:43]: not-blocking
```suggestion
    for version, result in zip(workload_version, results):
```

**Review by rgildein — CHANGES_REQUESTED** [review]
We are also missing tests for `generate_openstack_lookup`.

**Review by esunar — CHANGES_REQUESTED** [review]

File: cou/utils/openstack.py (hunk 6 above)
Comment (esunar) [reply cou/utils/openstack.py:66]: parameter of `__init__` method would be nicer(still constant).

Comment (rgildein) [reply cou/utils/openstack.py:66]: it could be default value as constant, but you are right it can be configurable. However with __init__ this object will be generate anytime when it's called, so I think using `__new__` would be better here.

File: cou/utils/openstack.py [hunk 9]
```diff
@@ -13,118 +13,125 @@
...
-def get_ovn_codename(version):
-    """Determine OpenStack codename that corresponds to OVN version.
 
-    :param version: Version of OVN
-    :type version: string
-    :returns: Codename for OVN
-    :rtype: string
-    """
-    return _get_special_codename(version, OVN_CODENAMES)
+def generate_openstack_lookup() -> OrderedDict:
```
[the remark this answers is not in the document]
Comment (aieri) [reply cou/utils/openstack.py:35]: I agree. On the other hand, as a user of the library it would be a lot more natural to import and use a function directly (e.g. `get_compatible_codename` instead of having to first instantiate a "Comparer" object. We could still handle `generate_openstack_lookup` as a class `__init__` internally though

File: cou/utils/openstack.py (hunk 4 above)
[the remark this answers is not in the document]
Comment (aieri) [reply cou/utils/openstack.py:96]: if your aim is to not regenerate the dictionary for every call a `@cache` decorator should suffice. If we opt for a class I agree with Robert's proposal

File: cou/utils/openstack.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (aieri) [reply cou/utils/openstack.py:124]: Right, or more precisely (though equivalently) `upper` would be the first incompatible version. Perhaps you can find a better name for it.
In order to handle the latest version of a component we would need to handle an unbound `upper` limit (i.e. the default value for `upper` should be `None` and the return boolean should be `True` as long as `testver >= lowerver`). This was just a small example, feel free to rework and expand as needed.

File: cou/utils/os_versions.py [hunk 10]
```diff
@@ -18,74 +18,6 @@
 from collections import OrderedDict
 from typing import List, Optional
 
-SERVICE_GROUPS = (
```
[the remark this answers is not in the document]
Comment (aieri) [reply cou/utils/os_versions.py:21]: SERVICE_GROUPS is a separate concept from codename compatibility. I would propose having two independent mappings.

**Review by aieri — CHANGES_REQUESTED** [review]

File: cou/utils/openstack.py (hunk 9 above)
[the remark this answers is not in the document]
Comment (rgildein) [reply cou/utils/openstack.py:59]: The `generate_openstack_lookup` could return the object itself, however I agree that with Gabriel that we do not need to initialized it every-time when someone call `generate_openstack_lookup`, so we can follow singleton pattern here.

File: cou/steps/analyze.py [hunk 11]
```diff
@@ -127,8 +127,15 @@ def __post_init__(self) -> None:
...
             self.units[unit]["workload_version"] = workload_version
-            os_version = get_latest_compatible_openstack_codename(self.charm, workload_version)
-            self.units[unit]["os_version"] = os_version
+            possible_os_versions = openstack_lookup.get_compatible_openstack_codenames(
+                self.charm, workload_version
+            )
+            if len(possible_os_versions) == 1:
+                self.units[unit]["os_version"] = possible_os_versions[0]
+            elif len(possible_os_versions) > 1:
+                self.units[unit]["os_version"] = possible_os_versions[-1]
```
Comment (rgildein) [inline cou/steps/analyze.py:136]: I think this is not needed, because there is no difference to get last object in list and first object if length is 1.
```python
if len(possible_os_versions) == 1:
  assert possible_os_versions[0] == possible_os_versions[-1]
```

Comment (rgildein) [reply cou/steps/analyze.py:136]: Plus I will provide simple comment like "Getting latest possible os version".

File: cou/utils/openstack.py [hunk 12]
```diff
@@ -13,125 +13,129 @@
...
+        """Magic method to check if a version is between the range.
+
+        :param version: version of a service.
+        :type version: str
+        :return: True if version is in the range.
+        :rtype: bool
+        """
+        service_version = Version(version)
+        if self.lower == self.upper:
+            return service_version >= self.lower and service_version <= self.upper
```
[the remark this answers is not in the document]
Comment (rgildein) [reply cou/utils/openstack.py:55]: I was going to suggest to use simply `if self.lower == self.upper == service_version: return True`, but Andrea is right here we should stick with default behavior of range here.

File: cou/utils/openstack.py [hunk 13]
```diff
@@ -13,125 +13,129 @@
...
+    for charm_type, charms in CHARM_TYPES.items():
         for charm in charms:
             openstack_lookup[charm] = openstack_lookup[charm_type]
     return openstack_lookup
 
 
-OPENSTACK_LOOKUP = generate_openstack_lookup()
-
+class OpenStackLookup(object):
+    _OPENSTACK_LOOKUP: OrderedDict = OrderedDict()
```
Comment (rgildein) [inline cou/utils/openstack.py:100]:
```suggestion
    _OPENSTACK_LOOKUP: Optional[OrderedDict] = None
```

File: cou/utils/openstack.py [hunk 14]
```diff
@@ -13,125 +13,129 @@
...
+
+    def __new__(cls):
+        """Magic method for create the OpenStackLookup object.
+
+        :return: OpenStackLookup object
+        :rtype: OpenStackLookup
+        """
+        if not cls._OPENSTACK_LOOKUP:
```
Comment (rgildein) [inline cou/utils/openstack.py:108]: It should more stable to check if value is None, rather than empty dict. I know that the `generate_openstack_lookup` should never return empty dictionary, but still is good practice.
```suggestion
        if cls._OPENSTACK_LOOKUP is None:
```

File: cou/utils/openstack.py [hunk 15]
```diff
@@ -13,125 +13,129 @@
...
+        """Get the possible OpenStack codenames based on the component and version.
+
+        :param component: Name of the component. E.g: "keystone"
+        :type component: str
+        :param version: Version of the component. E.g: "17.0.2"
+        :type version: str
+        :return: Return a list with the compatible OpenStack codenames.
+        :rtype: List[Optional[str]]
+        """
+        possible_os_releases: List[Optional[str]] = []
```
Comment (rgildein) [inline cou/utils/openstack.py:124]: In what case the `openstack_release` can be None? If there is situation like that I think we should not append it to the list.

**Review by rgildein — CHANGES_REQUESTED** [review]
It look almost good to me, couple suggestions.

File: cou/utils/openstack.py [hunk 16]
```diff
@@ -13,118 +13,129 @@
...
+                version,
+            )
+            return possible_os_releases
+        for openstack_release, version_range in self._OPENSTACK_LOOKUP[component].items():
+            if version in version_range:
+                possible_os_releases.append(openstack_release)
+        return possible_os_releases
+
+
+openstack_lookup = OpenStackLookup()
```
Comment (esunar) [inline cou/utils/openstack.py:141]: Running code which has side effects while importing module is bad practice. For example if they do not have csv file it will throw file not found error when they import module.  Maybe something like:
```python
class OpenStackCodenameLookup(object):
    _OPENSTACK_LOOKUP: OrderedDict = OrderedDict()
    _DEFAULT_CSV_FILE = "cou/utils/openstack_lookup.csv"
   
    @classmethod
    def initialize_lookup(cls, resource: Optional[File]):
        file_to_import = resource
        if not file_to_import:
            file_to_import = _DEFAULT_CSV_FILE
        cls._OPENSTACK_LOOKUP = _generate_lookup(file_to_import)

    @classmethod
    def lookup(cls, component: str, version: str) -> List[Optional[str]]:
       if not initialized:
           initialize_lookup
        ...
    @classmethod
    def _generate_lookup(cls, file_to_import):
        ...
```

File: cou/utils/openstack_lookup.csv
[the remark this answers is not in the document]
Comment (gabrielcocenza) [reply cou/utils/openstack_lookup.csv:1]: We are currently trying to use [packaging](https://packaging.pypa.io/en/latest/version.html#) to facilitate the comparison of versions in a certain package. It's not possible to create a `Version` object passing `None` or empty string `""`.
I see two possible solutions in this case:

1. Keep the strategy of `lower` and `upper` being the same and have a inclusive comparison (like the code is right now)
2. Create a `fake` version that is bigger than what we currently have and update to the correct value when it is released. E.g: MySQL charms are `8.0` from `ussuri` to `bobcat` and we create a fake `9.0` to be the `upper`.

I slightly prefer the first option.

We have also another issue that might need to be addressed in this patch. For OpenStack charms changing the ubuntu series from `focal` to `jammy` on `yoga` won't change the service version, but it might change for other charms like `rabbitmq` that should be 3.8 on focal and 3.9 on jammy.

```
----> 1 Version("")

File ~/Documents/canonical/charmed-openstack-upgrader-1/.venv/lib/python3.10/site-packages/packaging/version.py:198, in Version.__init__(self, version)
    196 match = self._regex.search(version)
    197 if not match:
--> 198     raise InvalidVersion(f"Invalid version: '{version}'")
    200 # Store the parsed out pieces of the version
    201 self._version = _Version(
    202     epoch=int(match.group("epoch")) if match.group("epoch") else 0,
    203     release=tuple(int(i) for i in match.group("release").split(".")),
   (...)
    209     local=_parse_local_version(match.group("local")),
    210 )

InvalidVersion: Invalid version: ''
```
```
----> 1 Version(None)

File ~/Documents/canonical/charmed-openstack-upgrader-1/.venv/lib/python3.10/site-packages/packaging/version.py:196, in Version.__init__(self, version)
    185 """Initialize a Version object.
    186 
    187 :param version:
   (...)
    192     exception will be raised.
    193 """
    195 # Validate the version and parse it into pieces
--> 196 match = self._regex.search(version)
    197 if not match:
    198     raise InvalidVersion(f"Invalid version: '{version}'")

TypeError: expected string or bytes-like object
```

File: cou/utils/openstack.py (hunk 13 above)
Comment (gabrielcocenza) [reply cou/utils/openstack.py:100]: I tried to use like this before, but mypy will complain:
```
cou/utils/openstack.py:125: error: Item "None" of "OrderedDict[Any, Any] | None" has no attribute "get"  [union-attr]
cou/utils/openstack.py:135: error: Value of type "OrderedDict[Any, Any] | None" is not indexable  [index]
``` 
Line 125 : `if not self._OPENSTACK_LOOKUP.get(component)`
Line 135: `openstack_release, version_range in self._OPENSTACK_LOOKUP[component].items()`

Should I disable mypy on those lines? I didn't figure out a way to handle this

File: cou/utils/openstack.py (hunk 16 above)
Comment (aieri) [reply cou/utils/openstack.py:141]: yes, I agree that an import should not yield an exception. However let's consider that the csv file would be part of the codebase, so failing to find it and read it is equivalent to failing to find or read any other Python file we're delivering as part of this snap

File: cou/utils/openstack_lookup.csv
[the remark this answers is not in the document]
Comment (aieri) [reply cou/utils/openstack_lookup.csv:1]: As discussed elsewhere, we'll stick to giving lower and upper bounds for every OpenStack codename for simplicity.
Regarding the question around differences between Ubuntu series and rabbitmq versioning, I tentatively think that the Ubuntu series doesn't matter: Ussuri to Xena require rabbitmq 3.8, Yoga is ok with either 3.8 or 3.9, while Zed and above need 3.9 (they may actually work with 3.8, but I doubt anyone has tested the combination). The fact that 3.8 is in Focal and 3.9 is in Jammy is an implementation detail: it will mean that when you need to upgrade from 3.8 to 3.9 you'll need to do a series upgrade.

File: cou/utils/openstack.py [hunk 17]
```diff
@@ -13,118 +13,138 @@
...
-    :rtype: string
-    """
-    return _get_special_codename(version, OVN_CODENAMES)
-
-
-def _get_special_codename(version, codenames):
-    found = [k for k, v in six.iteritems(codenames) if version in v]
-    return found[0]
+@dataclass(frozen=True)
+class VersionRange:
```
[the remark this answers is not in the document]
Comment (gabrielcocenza) [reply cou/utils/openstack.py:40]: I tried to use like this:
```python3
from collections.abc import Container

@dataclass(frozen=True)
class VersionRange(Container):
    lower: str
    upper: str
    ......
```

`mypy` complains with this:
```
lint: commands[2]> mypy --install-types --non-interactive .
cou/utils/openstack.py:45: error: Argument 1 of "__contains__" is incompatible with supertype "Container"; supertype defines the argument type as "object"  [override]
Found 1 error in 1 file (checked 11 source files)
cou/utils/openstack.py:45: note: This violates the Liskov substitution principle
cou/utils/openstack.py:45: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
lint: exit 1 (0.44 seconds) /home/cocenza/Documents/canonical/charmed-openstack-upgrader-1> mypy --install-types --non-interactive . pid=323823
  lint: FAIL code 1 (7.78=setup[0.03]+cmd[0.22,7.09,0.44] seconds)
  evaluation failed :( (7.81 seconds)
make: *** [Makefile:28: lint] Error 1
```
I think it's because `Container` is an abstract class, than it violates the Liskov substitution principle

[the remark this answers is not in the document]
Comment (gabrielcocenza) [reply cou/utils/openstack.py:40]: I gave a deeper look and if we change to something like this it will work:

```
@dataclass(frozen=True)
class VersionRange(Container):
    lower: str
    upper: str

    def __contains__(self, version: Any) -> bool:
```

The problem was that in the abstract implementation `x` is more generic than the `str`. changing to `Any` or using `# type: ignore[override]` will solve this mypy problem, but I think it does not worth inheriting it. It would be the same inheriting `Hashable` if we want to implement a custom `__hash__` method.

**Review by aieri — APPROVED** [review]
